### ISSUE TITLE
Будет ли поддержка питона3?

### ISSUE THREAD

**Issue by elec2105** [crabvk/plugin.video.movix#2]
Будет ли поддержка питона3? плагин использую нравится, в принципе все устраивает, только 2 нюанса
-на коди 19 не запускается
-раз в месяц примерно, требуется очищать кэш и по новой логинится

**Comment by elec2105** [comment]
Плюс если не сложно, можешь пожалуйста прикрутить iptv manager, как тут http://xbmc.ru/forum/showthread.php?p=148740#post148740

**Comment by crabvk** [comment]
Добавил пока в задачи обновление токена (через месяц использования плагина) и интеграцию с IPTV Manager https://github.com/crabvk/plugin.video.movix/projects/1
Эта ишью по обновлению на питон 3 для Коди 19 пофикшена в версии 0.4.0
